/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import DAOs.UsuarioDAO;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import users.Sesion;

/**
 *
 * @author yeferson
 */
public class FrLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrLogin.class.getName());

    UsuarioDAO userDAO = new UsuarioDAO();
    /**
     * Creates new form FrLogin
     */
    public FrLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    
    private void showCard(String card){
        CardLayout cl = (CardLayout)pnlCardLogin.getLayout();
        cl.show(pnlCardLogin, card);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgLogin = new javax.swing.JPanel();
        containerButton = new javax.swing.JPanel();
        btnRegister = new javax.swing.JPanel();
        lbRegister = new javax.swing.JLabel();
        btnLoginCard = new javax.swing.JPanel();
        lbLogin = new javax.swing.JLabel();
        pnlCardLogin = new javax.swing.JPanel();
        cardLogin = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        txtUsuarioLogin = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassLogin = new javax.swing.JPasswordField();
        cardRegister = new javax.swing.JPanel();
        lbCrearPass = new javax.swing.JLabel();
        lbCrearUser = new javax.swing.JLabel();
        txtUserRegister = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        txtPassRegister = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgLogin.setBackground(new java.awt.Color(255, 255, 255));

        containerButton.setBackground(new java.awt.Color(255, 255, 255));
        containerButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbRegister.setBackground(new java.awt.Color(255, 255, 255));
        lbRegister.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbRegister.setForeground(new java.awt.Color(59, 130, 246));
        lbRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegister.setText("Register");
        lbRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbRegisterMouseClicked(evt);
            }
        });
        btnRegister.add(lbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        containerButton.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 135, 40));

        btnLoginCard.setBackground(new java.awt.Color(51, 0, 255));
        btnLoginCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogin.setBackground(new java.awt.Color(59, 130, 246));
        lbLogin.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("Login");
        lbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLoginMouseClicked(evt);
            }
        });
        btnLoginCard.add(lbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 40));

        containerButton.add(btnLoginCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 135, 40));

        pnlCardLogin.setBackground(new java.awt.Color(51, 255, 255));
        pnlCardLogin.setLayout(new java.awt.CardLayout());

        cardLogin.setBackground(new java.awt.Color(59, 130, 246));
        cardLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsuario.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lbUsuario.setText("Usuario");
        cardLogin.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        txtUsuarioLogin.setBackground(new java.awt.Color(59, 130, 246));
        txtUsuarioLogin.setBorder(null);
        cardLogin.add(txtUsuarioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, 20));

        lbPassword.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbPassword.setForeground(new java.awt.Color(255, 255, 255));
        lbPassword.setText("Password");
        cardLogin.add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(59, 130, 246));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        cardLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 250, 90, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        cardLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        cardLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 160, 10));

        txtPassLogin.setBackground(new java.awt.Color(59, 130, 246));
        txtPassLogin.setBorder(null);
        cardLogin.add(txtPassLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, 20));

        pnlCardLogin.add(cardLogin, "cardLogin");

        cardRegister.setBackground(new java.awt.Color(255, 255, 255));
        cardRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 130, 246)));
        cardRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCrearPass.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbCrearPass.setForeground(new java.awt.Color(59, 130, 246));
        lbCrearPass.setText("Crea una contraseña");
        cardRegister.add(lbCrearPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        lbCrearUser.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lbCrearUser.setForeground(new java.awt.Color(59, 130, 246));
        lbCrearUser.setText("Crea un usuario");
        cardRegister.add(lbCrearUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        txtUserRegister.setBackground(new java.awt.Color(255, 255, 255));
        txtUserRegister.setBorder(null);
        cardRegister.add(txtUserRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 160, 30));

        jSeparator3.setForeground(new java.awt.Color(59, 130, 246));
        cardRegister.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 160, 10));

        jSeparator4.setForeground(new java.awt.Color(59, 130, 246));
        cardRegister.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, 10));

        jButton1.setBackground(new java.awt.Color(59, 130, 246));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        cardRegister.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 100, 30));

        txtPassRegister.setBackground(new java.awt.Color(255, 255, 255));
        txtPassRegister.setBorder(null);
        cardRegister.add(txtPassRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 150, 30));

        pnlCardLogin.add(cardRegister, "cardRegister");

        javax.swing.GroupLayout bgLoginLayout = new javax.swing.GroupLayout(bgLogin);
        bgLogin.setLayout(bgLoginLayout);
        bgLoginLayout.setHorizontalGroup(
            bgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLoginLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(bgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        bgLoginLayout.setVerticalGroup(
            bgLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLoginLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(containerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(bgLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLoginMouseClicked
        showCard("cardLogin");
    }//GEN-LAST:event_lbLoginMouseClicked

    private void lbRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbRegisterMouseClicked
        showCard("cardRegister");
    }//GEN-LAST:event_lbRegisterMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String user = txtUsuarioLogin.getText();
        String pass = txtPassLogin.getText();
        
        if(userDAO.loginUser(user, pass)){
            
            JOptionPane.showMessageDialog(null, "Bienvenido");
//            Sesion.idUsuario = userDAO.obtenerIdUsuario(user);
//             int id = Sesion.idUsuario;
             FrZoomascotas ventanaZoo =  new FrZoomascotas(user);
             ventanaZoo.setVisible(true);
            dispose();
        }else{
           JOptionPane.showMessageDialog(null, "EL usuario o contradeña no coinciden"); 
        }
        
        txtUsuarioLogin.setText("");
        txtPassLogin.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String user = txtUserRegister.getText();
        String pass = txtPassRegister.getText();
        
        if(userDAO.registerUser(user, pass))
            JOptionPane.showMessageDialog(null, "Usuario registrado"); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgLogin;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel btnLoginCard;
    private javax.swing.JPanel btnRegister;
    private javax.swing.JPanel cardLogin;
    private javax.swing.JPanel cardRegister;
    private javax.swing.JPanel containerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbCrearPass;
    private javax.swing.JLabel lbCrearUser;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JPanel pnlCardLogin;
    private javax.swing.JPasswordField txtPassLogin;
    private javax.swing.JPasswordField txtPassRegister;
    private javax.swing.JTextField txtUserRegister;
    private javax.swing.JTextField txtUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
