/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import DAOs.CuidadorDAO;
import controlador.ReporteAnimal;
import controlador.ReporteCuidador;
import controlador.ReporteTraslados;
import controlador.ShowCard;
import java.util.Date;
import modelo.Cuidador;

/**
 *
 * @author yeferson
 */
public class FrReportes extends javax.swing.JFrame {
    
    String user;
    
    ReporteCuidador cuReporte = new ReporteCuidador();
    ReporteAnimal anReporte = new ReporteAnimal();
    ReporteTraslados trReporte = new ReporteTraslados();
    
    CuidadorDAO cuDAO = new CuidadorDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrReportes.class.getName());

    
    
    /**
     * Creates new form FrReportes
     */
    public FrReportes() {
        initComponents();
        setLocationRelativeTo(null);
        
        cuDAO.cargarCuidadoresCb(cbReporteCu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBgReporte = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlBtnCu = new javax.swing.JPanel();
        btnCuReporte = new javax.swing.JLabel();
        pnlBtnAnimal = new javax.swing.JPanel();
        btnAnReporte = new javax.swing.JLabel();
        pnlBtnZoo = new javax.swing.JPanel();
        btnReporteZoo = new javax.swing.JLabel();
        pnlCardsReportes = new javax.swing.JPanel();
        pnlCardCuidador = new javax.swing.JPanel();
        lbReporteCu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbFormatoCuCumple = new javax.swing.JComboBox<>();
        btnGenerarCuCumple = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        cbFormatoCu = new javax.swing.JComboBox<>();
        cbGeneroCu = new javax.swing.JComboBox<>();
        btnGenerarCu = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cbFormatoCuGenero = new javax.swing.JComboBox<>();
        btnGenerarGeneroCu = new javax.swing.JButton();
        cbReporteCu = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaCuFin = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        fechaCuInicio = new com.toedter.calendar.JDateChooser();
        cbFormatoCuAn = new javax.swing.JComboBox<>();
        btnGenerarAnCu = new javax.swing.JButton();
        pnlCardZoo = new javax.swing.JPanel();
        lbReporteZoo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbFormatoFechasTr = new javax.swing.JComboBox<>();
        btnTraslados = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbFormatoTraslados = new javax.swing.JLabel();
        fechaInicioTr = new com.toedter.calendar.JDateChooser();
        fechaFinTr = new com.toedter.calendar.JDateChooser();
        cbFormatoTr = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        pnlCardAnimal = new javax.swing.JPanel();
        lbReporteAn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbFormatoTodosAn = new javax.swing.JComboBox<>();
        btnTodosAn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cbFormatoTipoAn = new javax.swing.JComboBox<>();
        cbFormatoGeneroAn = new javax.swing.JComboBox<>();
        btnGeneroAn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        cbGeneroAn = new javax.swing.JComboBox<>();
        cbEstadoAn = new javax.swing.JComboBox<>();
        btnEstadoAn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cbFormatoEstado = new javax.swing.JComboBox<>();
        cbTipoAn = new javax.swing.JComboBox<>();
        btnTipoAn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBgReporte.setBackground(new java.awt.Color(255, 255, 255));
        pnlBgReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBtnCu.setBackground(new java.awt.Color(59, 130, 246));

        btnCuReporte.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnCuReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnCuReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCuReporte.setText("Cuidador");
        btnCuReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnCuLayout = new javax.swing.GroupLayout(pnlBtnCu);
        pnlBtnCu.setLayout(pnlBtnCuLayout);
        pnlBtnCuLayout.setHorizontalGroup(
            pnlBtnCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCuReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlBtnCuLayout.setVerticalGroup(
            pnlBtnCuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCuReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBtnCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 100, 40));

        pnlBtnAnimal.setBackground(new java.awt.Color(59, 130, 246));

        btnAnReporte.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnAnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnAnReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnReporte.setText("Animal");
        btnAnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnReporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnAnimalLayout = new javax.swing.GroupLayout(pnlBtnAnimal);
        pnlBtnAnimal.setLayout(pnlBtnAnimalLayout);
        pnlBtnAnimalLayout.setHorizontalGroup(
            pnlBtnAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlBtnAnimalLayout.setVerticalGroup(
            pnlBtnAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBtnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 100, 40));

        pnlBtnZoo.setBackground(new java.awt.Color(59, 130, 246));

        btnReporteZoo.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        btnReporteZoo.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteZoo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReporteZoo.setText("Tansferencia");
        btnReporteZoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteZooMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnZooLayout = new javax.swing.GroupLayout(pnlBtnZoo);
        pnlBtnZoo.setLayout(pnlBtnZooLayout);
        pnlBtnZooLayout.setHorizontalGroup(
            pnlBtnZooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReporteZoo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBtnZooLayout.setVerticalGroup(
            pnlBtnZooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReporteZoo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(pnlBtnZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 100, 40));

        pnlBgReporte.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 550, 90));

        pnlCardsReportes.setBackground(new java.awt.Color(255, 255, 255));
        pnlCardsReportes.setLayout(new java.awt.CardLayout());

        pnlCardCuidador.setBackground(new java.awt.Color(59, 130, 246));
        pnlCardCuidador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbReporteCu.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbReporteCu.setForeground(new java.awt.Color(255, 255, 255));
        lbReporteCu.setText("Reporte Cuidador");
        pnlCardCuidador.add(lbReporteCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 18, -1, -1));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Todos los cuidadores");
        pnlCardCuidador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        cbFormatoCuCumple.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardCuidador.add(cbFormatoCuCumple, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 110, -1));

        btnGenerarCuCumple.setText("Generar");
        btnGenerarCuCumple.addActionListener(this::btnGenerarCuCumpleActionPerformed);
        pnlCardCuidador.add(btnGenerarCuCumple, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardCuidador.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 550, 10));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Genero");
        pnlCardCuidador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        cbFormatoCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardCuidador.add(cbFormatoCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 130, -1));

        cbGeneroCu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERO", "MASCULINO", "FEMENINO" }));
        pnlCardCuidador.add(cbGeneroCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        btnGenerarCu.setText("Generar");
        btnGenerarCu.addActionListener(this::btnGenerarCuActionPerformed);
        pnlCardCuidador.add(btnGenerarCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardCuidador.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 550, 10));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AnimalesXcuidador");
        pnlCardCuidador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        cbFormatoCuGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardCuidador.add(cbFormatoCuGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 110, -1));

        btnGenerarGeneroCu.setText("Generar");
        btnGenerarGeneroCu.addActionListener(this::btnGenerarGeneroCuActionPerformed);
        pnlCardCuidador.add(btnGenerarGeneroCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        pnlCardCuidador.add(cbReporteCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 150, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardCuidador.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 550, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cumpleaños");
        pnlCardCuidador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Inicio");
        pnlCardCuidador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));
        pnlCardCuidador.add(fechaCuFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 120, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fin");
        pnlCardCuidador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        pnlCardCuidador.add(fechaCuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 120, -1));

        cbFormatoCuAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardCuidador.add(cbFormatoCuAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 110, -1));

        btnGenerarAnCu.setText("Generar");
        btnGenerarAnCu.addActionListener(this::btnGenerarAnCuActionPerformed);
        pnlCardCuidador.add(btnGenerarAnCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        pnlCardsReportes.add(pnlCardCuidador, "cardReporteCu");

        pnlCardZoo.setBackground(new java.awt.Color(59, 130, 246));
        pnlCardZoo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbReporteZoo.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbReporteZoo.setForeground(new java.awt.Color(255, 255, 255));
        lbReporteZoo.setText("REPORTE TRASLADOS");
        pnlCardZoo.add(lbReporteZoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Todos los traslados");
        pnlCardZoo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cbFormatoFechasTr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardZoo.add(cbFormatoFechasTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 160, -1));

        btnTraslados.setText("Generar");
        btnTraslados.addActionListener(this::btnTrasladosActionPerformed);
        pnlCardZoo.add(btnTraslados, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardZoo.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 550, 10));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Traslados por fecha");
        pnlCardZoo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fin");
        pnlCardZoo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        cbFormatoTraslados.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cbFormatoTraslados.setForeground(new java.awt.Color(255, 255, 255));
        cbFormatoTraslados.setText("Inicio");
        pnlCardZoo.add(cbFormatoTraslados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        pnlCardZoo.add(fechaInicioTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 130, -1));
        pnlCardZoo.add(fechaFinTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 130, -1));

        cbFormatoTr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardZoo.add(cbFormatoTr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        jButton2.setText("Generar");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        pnlCardZoo.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        pnlCardsReportes.add(pnlCardZoo, "cardReporteZoo");

        pnlCardAnimal.setBackground(new java.awt.Color(59, 130, 246));
        pnlCardAnimal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbReporteAn.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lbReporteAn.setForeground(new java.awt.Color(255, 255, 255));
        lbReporteAn.setText("Reporte Animal");
        pnlCardAnimal.add(lbReporteAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Todos los animales");
        pnlCardAnimal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cbFormatoTodosAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardAnimal.add(cbFormatoTodosAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 140, -1));

        btnTodosAn.setText("Generar");
        btnTodosAn.addActionListener(this::btnTodosAnActionPerformed);
        pnlCardAnimal.add(btnTodosAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardAnimal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 10));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Genero");
        pnlCardAnimal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbFormatoTipoAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardAnimal.add(cbFormatoTipoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 140, -1));

        cbFormatoGeneroAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardAnimal.add(cbFormatoGeneroAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 140, -1));

        btnGeneroAn.setText("Generar");
        btnGeneroAn.addActionListener(this::btnGeneroAnActionPerformed);
        pnlCardAnimal.add(btnGeneroAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardAnimal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 550, 10));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Estado");
        pnlCardAnimal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cbGeneroAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENERO", "Macho", "Hembra" }));
        pnlCardAnimal.add(cbGeneroAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, -1));

        cbEstadoAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        pnlCardAnimal.add(cbEstadoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 140, -1));

        btnEstadoAn.setText("Generar");
        btnEstadoAn.addActionListener(this::btnEstadoAnActionPerformed);
        pnlCardAnimal.add(btnEstadoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo");
        pnlCardAnimal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        pnlCardAnimal.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 550, 10));

        cbFormatoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FORMATO", "TXT", "EXCEL" }));
        pnlCardAnimal.add(cbFormatoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 140, -1));

        cbTipoAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO", "Anfibio", "Mamifero", "Reptil", "Ave" }));
        pnlCardAnimal.add(cbTipoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 140, -1));

        btnTipoAn.setText("Generar");
        btnTipoAn.addActionListener(this::btnTipoAnActionPerformed);
        pnlCardAnimal.add(btnTipoAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        pnlCardsReportes.add(pnlCardAnimal, "cardReporteAn");

        pnlBgReporte.add(pnlCardsReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 550, 350));

        jButton1.setText("Regresar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlBgReporte.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(pnlBgReporte, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCuReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuReporteMouseClicked
        cuDAO.cargarCuidadoresCb(cbReporteCu);
        ShowCard.showCard("cardReporteCu", pnlCardsReportes);
    }//GEN-LAST:event_btnCuReporteMouseClicked

    private void btnAnReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnReporteMouseClicked
        ShowCard.showCard("cardReporteAn", pnlCardsReportes);
    }//GEN-LAST:event_btnAnReporteMouseClicked

    private void btnReporteZooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteZooMouseClicked
        ShowCard.showCard("cardReporteZoo", pnlCardsReportes);
    }//GEN-LAST:event_btnReporteZooMouseClicked

    private void btnGenerarCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCuActionPerformed
        int formato = cbFormatoCu.getSelectedIndex();
        String query ="SELECT * FROM cuidador";
        switch( formato ){
            case 1 -> cuReporte.reporteCuidadores("Cuidadores.txt", "\t");
            case 2 -> cuReporte.reporteCuidadores("Cuidadores.xls", "\t");
            default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
        }
    }//GEN-LAST:event_btnGenerarCuActionPerformed

    private void btnGenerarGeneroCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarGeneroCuActionPerformed
        int formato = cbFormatoCuGenero.getSelectedIndex();
        String genero = cbGeneroCu.getSelectedItem().toString().trim();
        
        if( genero.equals("MASCULINO") || genero.equals("FEMENINO") ){
            switch( formato ){
                case 1 -> cuReporte.reporteGeneroCu("GeneroCuidadores.txt", genero, "\t");
                case 2 -> cuReporte.reporteGeneroCu("GeneroCuidadores.xls", genero, "\t");
                
                default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
            }
        }else
            javax.swing.JOptionPane.showMessageDialog(null, "Debe elejir un genero");
                               
    }//GEN-LAST:event_btnGenerarGeneroCuActionPerformed

    private void btnGenerarAnCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAnCuActionPerformed
        Cuidador cu = (Cuidador)cbReporteCu.getSelectedItem();
        int formato = cbFormatoCuAn.getSelectedIndex();
        
        if( cu != null ){
            switch( formato ){
                case 1 -> cuReporte.reporteAnACargo("AnimalesACargo.txt", cu, "\t");
                case 2 -> cuReporte.reporteAnACargo("AnimalesACargo.xls", cu, "\t");
                
                default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
            }
        }else
            javax.swing.JOptionPane.showMessageDialog(null, "Debe elejir un cuidador");
    }//GEN-LAST:event_btnGenerarAnCuActionPerformed

    private void btnGenerarCuCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCuCumpleActionPerformed
        Date inicio = fechaCuInicio.getDate();
        Date fin = fechaCuFin.getDate();
        int formato = cbFormatoCuCumple.getSelectedIndex();
        
        if( inicio != null ){
            if( fin != null ){
                switch( formato ){
                    case 1 -> cuReporte.reporteCumpleCu("CumpleañosCu.txt", inicio, fin, "\t");
                    case 2 -> cuReporte.reporteCumpleCu("CumpleañosCu.xls", inicio, fin, "\t");
                   
                    default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
                }
            }else
                javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar la fecha de fin");
        }else
            javax.swing.JOptionPane.showMessageDialog(null, "Debe ingresar la fecha de inicio");
    }//GEN-LAST:event_btnGenerarCuCumpleActionPerformed

    private void btnTodosAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosAnActionPerformed
         int formato = cbFormatoTodosAn.getSelectedIndex();

        switch(formato){
            case 1 -> anReporte.reporteAnimales("Animales.txt", "\t");
            case 2 -> anReporte.reporteAnimales("Animales.xls", "\t");
            
            default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
        }
    }//GEN-LAST:event_btnTodosAnActionPerformed

    private void btnGeneroAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneroAnActionPerformed
         String genero = cbGeneroAn.getSelectedItem().toString().trim();
        int formato = cbFormatoGeneroAn.getSelectedIndex();

        if( genero.equals("Hembra") || genero.equals("Macho") ){
            switch( formato ){
                case 1 -> anReporte.reporteGeneroAn("GeneroAnimales.txt", genero, "\t");
                case 2 -> anReporte.reporteGeneroAn("GeneroAnimales.xls", genero, "\t");
                
                default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
            }
        }else
        javax.swing.JOptionPane.showMessageDialog(null, "Elije un genero");
    }//GEN-LAST:event_btnGeneroAnActionPerformed

    private void btnTipoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoAnActionPerformed
        String tipo = cbTipoAn.getSelectedItem().toString().trim();
        int formato = cbFormatoTipoAn.getSelectedIndex();

        if( tipo.equals("Anfibio") || tipo.equals("Mamifero") || tipo.equals("Reptiel") || tipo.equals("Ave") ){
            switch( formato ){
                case 1 -> anReporte.reporteTipoAn("TipoAnimal.txt", tipo, "\t");
                case 2 -> anReporte.reporteTipoAn("TipoAnimal.xls", tipo, "\t");
               
                default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
            }
        }else
        javax.swing.JOptionPane.showMessageDialog(null, "Elije un tipo");
    }//GEN-LAST:event_btnTipoAnActionPerformed

    private void btnEstadoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoAnActionPerformed
         String estado = cbEstadoAn.getSelectedItem().toString().trim();
        int formato = cbFormatoEstado.getSelectedIndex();

        if( estado.equals("Activo") || estado.equals("Inactivo") ){
            switch( formato ){
                case 1 -> anReporte.reporteEstadoAn("Estado.txt", estado, "\t");
                case 2 -> anReporte.reporteEstadoAn("Estado.xls", estado, "\t");
               
                default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
            }

        }else
        javax.swing.JOptionPane.showMessageDialog(null, "Elije un estado");
    }//GEN-LAST:event_btnEstadoAnActionPerformed

    private void btnTrasladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladosActionPerformed
          int formato = cbFormatoTr.getSelectedIndex();

        switch( formato ){
            case 1 -> trReporte.reporteTr("TrasladosAnimales.txt", "\t");
            case 2 -> trReporte.reporteTr("TrasladosAnimales.xls", "\t");
            
            default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
        }
    }//GEN-LAST:event_btnTrasladosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date inicio = fechaInicioTr.getDate();
        Date fin = fechaFinTr.getDate();
        int formato = cbFormatoFechasTr.getSelectedIndex();

        if( inicio != null){
            if( fin != null ){
                switch( formato ){
                    case 1 -> trReporte.reporteFechasTr("TrasladosFechas.txt", inicio, fin, "\t");
                    case 2 -> trReporte.reporteFechasTr("TrasladosFechas.xls", inicio, fin, "\t");
                   
                    default -> javax.swing.JOptionPane.showMessageDialog(null, "Elije un formato");
                }

            }else
            javax.swing.JOptionPane.showMessageDialog(null, "Ingrese la fecha final");
        }else
        javax.swing.JOptionPane.showMessageDialog(null, "Ingrese la fecha de inicio");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FrZoomascotas ventanaMain = new FrZoomascotas();
        ventanaMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new FrReportes().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnReporte;
    private javax.swing.JLabel btnCuReporte;
    private javax.swing.JButton btnEstadoAn;
    private javax.swing.JButton btnGenerarAnCu;
    private javax.swing.JButton btnGenerarCu;
    private javax.swing.JButton btnGenerarCuCumple;
    private javax.swing.JButton btnGenerarGeneroCu;
    private javax.swing.JButton btnGeneroAn;
    private javax.swing.JLabel btnReporteZoo;
    private javax.swing.JButton btnTipoAn;
    private javax.swing.JButton btnTodosAn;
    private javax.swing.JButton btnTraslados;
    private javax.swing.JComboBox<String> cbEstadoAn;
    private javax.swing.JComboBox<String> cbFormatoCu;
    private javax.swing.JComboBox<String> cbFormatoCuAn;
    private javax.swing.JComboBox<String> cbFormatoCuCumple;
    private javax.swing.JComboBox<String> cbFormatoCuGenero;
    private javax.swing.JComboBox<String> cbFormatoEstado;
    private javax.swing.JComboBox<String> cbFormatoFechasTr;
    private javax.swing.JComboBox<String> cbFormatoGeneroAn;
    private javax.swing.JComboBox<String> cbFormatoTipoAn;
    private javax.swing.JComboBox<String> cbFormatoTodosAn;
    private javax.swing.JComboBox<String> cbFormatoTr;
    private javax.swing.JLabel cbFormatoTraslados;
    private javax.swing.JComboBox<String> cbGeneroAn;
    private javax.swing.JComboBox<String> cbGeneroCu;
    private javax.swing.JComboBox<String> cbReporteCu;
    private javax.swing.JComboBox<String> cbTipoAn;
    private com.toedter.calendar.JDateChooser fechaCuFin;
    private com.toedter.calendar.JDateChooser fechaCuInicio;
    private com.toedter.calendar.JDateChooser fechaFinTr;
    private com.toedter.calendar.JDateChooser fechaInicioTr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbReporteAn;
    private javax.swing.JLabel lbReporteCu;
    private javax.swing.JLabel lbReporteZoo;
    private javax.swing.JPanel pnlBgReporte;
    private javax.swing.JPanel pnlBtnAnimal;
    private javax.swing.JPanel pnlBtnCu;
    private javax.swing.JPanel pnlBtnZoo;
    private javax.swing.JPanel pnlCardAnimal;
    private javax.swing.JPanel pnlCardCuidador;
    private javax.swing.JPanel pnlCardZoo;
    private javax.swing.JPanel pnlCardsReportes;
    // End of variables declaration//GEN-END:variables
}
